### ISSUE TITLE
SEB can't open in google chrome

### ISSUE THREAD

**Issue by alihammoud90** [SafeExamBrowser/SafeExamBrowser-Website#10]
I tried to put the user agent for google chrome in seb configuration, but it is still launching in firefox.

User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36

Am I doing something wrong?

**Comment by Krisell** [comment]
If you mean that you want the built-in browser (which is Firefox for SEB 2 and Chrome for SEB 3) to change, that is not affected by the user-agent value.
